version: '3'

networks:
  auth:
    external:
      name: auth.reaction.localhost

services:

  hydra-migrate:
    image: oryd/hydra:v1.0.0-beta.9-alpine
    command: migrate sql -e
    depends_on:
      - postgres
    environment:
#      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://hydra:changeme@postgres:5432/hydra?sslmode=disable
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.0.0-beta.9-alpine
    command: serve all --dangerous-force-http
    depends_on:
      - hydra-migrate
      - postgres
#     Uncomment the following line to use mysql instead.
#      - mysqld:mysqld
    networks:
      default:
      auth:
    ports:
      # Public port
      - "4444:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    environment:
#      - LOG_LEVEL=debug
      - OAUTH2_ISSUER_URL=${OAUTH2_ISSUER_URL}
      - OAUTH2_CONSENT_URL=${OAUTH2_CONSENT_URL}
      - OAUTH2_LOGIN_URL=${OAUTH2_LOGIN_URL}
      - DATABASE_URL=${DATABASE_URL}
      - SYSTEM_SECRET=${SYSTEM_SECRET}
      - OAUTH2_SHARE_ERROR_DEBUG=${OAUTH2_SHARE_ERROR_DEBUG}
      - OIDC_SUBJECT_TYPES_SUPPORTED=${OIDC_SUBJECT_TYPES_SUPPORTED}
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=${OIDC_SUBJECT_TYPE_PAIRWISE_SALT}
#     - OAUTH2_ACCESS_TOKEN_STRATEGY=jwt
    restart: unless-stopped

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
